import type { Metadata } from "next";
import TopNavbar from '../app/ui/components/topNavbar'


export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
     <TopNavbar/>
    </div>
  );
}
